### ISSUE TITLE
mem access type typo

### ISSUE THREAD

**Issue by mpriestleyidex** [SystemRDL/RALBot-uvm#11]
In exporter.py:
```
    def _get_mem_access(self, mem: MemNode) -> str:
        sw = mem.get_property("sw")
        if sw == AccessType.r:
            return "R"
        else:
            return "RW"
```

I think the "R" should be an "RO". Certainly the UVM libraries I'm using think so, though I've not dived into any UVM specifications to find out for certain.

**Comment by amykyta3** [comment]
Fixed in v2.0.4. Thanks for finding this!
