### ISSUE TITLE
hello，dear ，the systemrdl have keyword msb0，lsb0；i add msb0 to my rdl ，but it do not work，the fields bits sequence not change ，hwo to solve the problem？

### ISSUE THREAD

**Issue by jiangqingliu88** [SystemRDL/RALBot-uvm#15]
the regblock also should   reverse fields sequnce。

**Comment by jiangqingliu88** [comment]
i use the other methods resolve the pronlem，the change is  struct packed{
                struct packed{
                    logic [11:0] value;
                } reserved;
                struct packed{
                    logic [3:0] value;
                } port3_role;
                struct packed{
                    logic [3:0] value;
                } port2_role;
                struct packed{
                    logic [3:0] value;
                } port1_role;
                struct packed{
                    logic [3:0] value;
                } port0_role;
                struct packed{
                    logic [3:0] value;
                } Switch_role;
            } cfg_reg;
so the backdoor is equal to the front door access  value。

**Comment by amykyta3** [comment]
Please provide more details. I do not understand what issue you are having.
