### ISSUE TITLE
I have implemented this function, can I merge?

### ISSUE THREAD

**Issue by zhajio1988** [SystemRDL/RALBot-uvm#2]
@amykyta3 

I have implemented this function, the scripts can generate UVM regmodel。
I have tested it used accelera-generic_example.rdl file.

**Comment by amykyta3** [comment]
Absolutely!
I haven't had much time to put this together so I appreciate the help.

I have added you as a collaborator to this repository. Feel free to push and we can work on creating a package.

**Comment by zhajio1988** [comment]
i will pull a version， i don‘t do unit test。But test use three *.rdl file directly。

**Comment by zhajio1988** [comment]
@amykyta3 
hi, This repository is empty. how can i execute P&R operation?
it's the first time i P&R code.
thanks.

**Comment by amykyta3** [comment]
I have imported it. Thanks!
