### ISSUE TITLE
default hdl_path support

### ISSUE THREAD

**Issue by hughjackson** [SystemRDL/RALBot-uvm#22]
peakrdl-regblock has a well defined structure. It would be nice if there was a way of having a switch (or some sort of pattern) to allow the generator to automatically use the regblock structure if no explicit hdl_path is defined

e.g. for field_storage.REG.FIELD.value:

- field_storage could be included in the reg_block hdl_path
- fields like FIELD would have hdl_path_slice '{"REG.FIELD.value"}

perhaps the option could be a pattern that allowed this to specified e.g. set_auto_hdl_path ("field_storage.{dot_path}.value", sliced=True). This would make it more useful to use alongside other regblock-like generators.

Another option is if there is an example of how to do something like this programmatically between compile and generation.

**Comment by amykyta3** [comment]
I actually plan to accomplish this via a mechanism from the regblock generator. See: https://github.com/SystemRDL/PeakRDL-regblock/issues/15

Plan is to first rewrite the UVM generator to address some existing issues with HDL paths.

**Comment by amykyta3** [comment]
Some more discussion here: https://github.com/orgs/SystemRDL/discussions/151

**Comment by hughjackson** [comment]
Looks good. I thought you'd probably already have a plan! Thanks for all the great work
